// Generated by LiveScript 1.2.0
(function(){
  module.exports = function(karma){
    return karma.set({
      basePath: "../",
      frameworks: ["ng-scenario"],
      files: ["test/e2e/**/*.ls"],
      exclude: [],
      reporters: ["progress"],
      port: 9876,
      runnerPort: 9100,
      colors: true,
      logLevel: karma.LOG_INFO,
      urlRoot: '/__karma/',
      autoWatch: true,
      browsers: ["Chrome", "PhantomJS"],
      captureTimeout: 60000,
      plugins: ['karma-ng-scenario', 'karma-live-preprocessor', 'karma-chrome-launcher', 'karma-phantomjs-launcher'],
      preprocessors: {
        '**/*.ls': ['live']
      },
      proxies: {
        '/': 'http://localhost:3333/'
      },
      singleRun: false
    });
  };
}).call(this);
